### ISSUE TITLE
Performance.

### ISSUE THREAD

**Issue by juliolitwin** [DennisCorvers/UnsafeCollections#1]
Yo,

Yet are there any plans for benchmarkings?
Thanks for keeping the fork still in development! :]

Cheers.

**Comment by DennisCorvers** [comment]
Yes! I will add some performance comparisons between .Net collections and the Native collections once I'm done with the implementation.

**Comment by DennisCorvers** [comment]
I'm currently satisfied with how the project looks. I will look into adding some performance comparisons when I next have available time.

I will randomly choose some collections/functions to compare against the relevant .Net implementations. There are simply far too many to cover them all.

**Comment by juliolitwin** [comment]
I'm wanting to use it in my projects, since I choose to use unsafe. Do you have any intention of adding anything with pools?

Has a collections project that works with pooled based on the official netcore collections:
https://github.com/jtmueller/Collections.Pooled

Could you choose random any of these collections for testing as well?
